name: Deploy to Oracle Instance

on:
  push:
    branches: [main]

jobs:
  deploy:
    environment: oracle-instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd dev/tilt-game
            git pull origin main
            cd client
            npm install
            npm run build
            cd ../server
            npm install
            cd ..
            pm2 restart tilt-game
